### ISSUE TITLE
Sundrinker has shipyard but no outfitter

### ISSUE THREAD

**Issue by TheGiraffe3** [mOctave/blended-ships#7]
**Describe the bug**
Sundrinker in the Alniyat has a shipyard, but not an outfitter.
This leads to a problem where you can buy Rawalpindis, but can't reoutfit them.
I believe it's probably best just to remove it altogether (or change it to Sunracer in Syndicate space)

**To Reproduce**
Land in Sundrinker.

**Expected behavior**
If you can buy ships, you should be able to reoutfit it them on the same planet.

**Information:**
 - ES Version: continuous
 - ES Source: GitHub
 - Blended Ships Source: latest commit

**Comment by mOctave** [comment]
You're right; there also probably wouldn't be any infrastructure there to support a shipyard. I have moved it to Zug.

**Comment by TheGiraffe3** [comment]
Alright, thanks for the fast responses!

**Comment by TheGiraffe3** [comment]
It looks like Canyon also has a shipyard but no outfitter, selling the Hare.

**Comment by mOctave** [comment]
Whoops.
